name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: contains(github.event.head_commit.message, '[actions skip]') == false
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: cache gradle packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk 21
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 21

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew


      - name: Build project
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: KotlinLibrary-${{ github.event.head_commit.sha }}
          path: build/libs/*.jar
